# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/token_data',
                'doc_host': 'https://silvaac.github.io',
                'git_url': 'https://github.com/silvaac/token_data',
                'lib_path': 'token_data'},
  'syms': {'token_data.core': {'token_data.core.foo': ('core.html#foo', 'token_data/core.py')}}}
