# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_coinbase.ipynb.

# %% auto 0
__all__ = ['CoinbaseDataSource']

# %% ../nbs/01_coinbase.ipynb 3
from .datasource import DataSource
from pathlib import Path
from typing import List
import polars as pl
import requests
import logging
from datetime import datetime, timedelta

# %% ../nbs/01_coinbase.ipynb 4
class CoinbaseDataSource(DataSource):
    """A data source for Coinbase."""

    def __init__(self, data_folder: Path):
        super().__init__(data_folder)
        self.api_url = "https://api.exchange.coinbase.com"

    def get_tokens(self) -> List[str]:
        """Returns a list of available tokens."""
        url = f"{self.api_url}/products"
        response = requests.get(url)
        response.raise_for_status()
        tokens = response.json()
        return [token['id'] for token in tokens]

    def get_prices(self, token: str, start_date: str, end_date: str, time_interval: int = 3600) -> pl.DataFrame:
        """Returns a DataFrame of prices for a given token."""
        url = f"{self.api_url}/products/{token}/candles"
        params = {
            'start': start_date,
            'end': end_date,
            'granularity': time_interval
        }
        response = requests.get(url, params=params)
        response.raise_for_status()
        data = response.json()
        if not data:
            return pl.DataFrame()
        
        df = pl.DataFrame(data, schema=[
            ('time', pl.Int64),
            ('low', pl.Float64),
            ('high', pl.Float64),
            ('open', pl.Float64),
            ('close', pl.Float64),
            ('volume', pl.Float64)
        ])
        df = df.with_columns([
            pl.from_epoch(pl.col('time'), time_unit='s').alias('datetime'),
            pl.lit(token).alias('token')
        ])
        return df.select(['datetime', 'open', 'high', 'low', 'close', 'volume', 'token'])
    
    def save_data(self, df: pl.DataFrame, token: str, file_type: str = 'parquet'):
        """Saves the data to a file."""
        super().save_data(df, token, file_type)

