# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_hyperliquid.ipynb.

# %% auto 0
__all__ = ['HyperliquidDataSource']

# %% ../nbs/02_hyperliquid.ipynb 3
from .datasource import DataSource
from pathlib import Path
from typing import List
import polars as pl
from hyperliquid.info import Info
from hyperliquid.utils import constants
import logging
from datetime import datetime, timedelta
import eth_account
import json

# %% ../nbs/02_hyperliquid.ipynb 4
class HyperliquidDataSource(DataSource):
    """A data source for Hyperliquid."""

    def __init__(self, data_folder: Path, config_path: str = '../config_hyperliquid.json'):
        super().__init__(data_folder)
        self.info = self._setup(config_path)

    def _setup(self, config_path: str):
        with open(config_path) as f:
            config = json.load(f)
        account = eth_account.Account.from_key(config["secret_key"])
        address = config.get("account_address") or account.address
        logging.info(f"Running with account address: {address}")
        return Info(constants.MAINNET_API_URL, skip_ws=True)

    def get_tokens(self) -> List[str]:
        """Returns a list of available tokens."""
        meta = self.info.meta()
        return [coin['name'] for coin in meta['universe']]

    def get_perp_prices(self, token: str, start_date: str, end_date: str, time_interval: str = '1h') -> pl.DataFrame:
        """Returns a DataFrame of perpetual prices for a given token."""
        start_time = int(datetime.fromisoformat(start_date.replace('Z', '')).timestamp() * 1000)
        end_time = int(datetime.fromisoformat(end_date.replace('Z', '')).timestamp() * 1000)
        candles = self.info.candles_snapshot(token, time_interval, start_time, end_time)
        if not candles:
            return pl.DataFrame()
        
        df = pl.DataFrame(candles)
        df = df.with_columns([
            pl.from_epoch(pl.col('t'), time_unit='ms').alias('datetime'),
            pl.lit(token).alias('token')
        ])
        return df.select(['datetime', 'o', 'h', 'l', 'c', 'v', 'token']).rename({'o': 'open', 'h': 'high', 'l': 'low', 'c': 'close', 'v': 'volume'})

    def get_spot_prices(self, token: str, start_date: str, end_date: str, time_interval: str = '1h') -> pl.DataFrame:
        """Returns a DataFrame of spot prices for a given token."""
        maps = self.info.spot_meta_and_asset_ctxs()
        if token.upper() == "ETH":
            coin = "UETH"
        elif token.upper() == "BTC":
            coin = "UBTC"
        else:
            coin = token

        id_coin, id_base = None, None
        for token_ctx in maps[0]['tokens']:
            if token_ctx['name'] == coin:
                id_coin = token_ctx['index']
            elif token_ctx['name'] == 'USDC':
                id_base = token_ctx['index']
        if id_coin is None or id_base is None:
            raise ValueError(f"Spot token {token} not found.")

        spot_token_name = None
        for i in maps[0]['universe']:
            if i['tokens'] == [id_coin,id_base]:
                spot_token_name = i['name']

        if not spot_token_name:
            raise ValueError(f"Spot token {token} not found.")

        return self.get_perp_prices(spot_token_name, start_date, end_date, time_interval)

    def get_funding_rates(self, token: str, start_date: str, end_date: str) -> pl.DataFrame:
        """Returns a DataFrame of funding rates for a given token."""
        start_time = int(datetime.fromisoformat(start_date.replace('Z', '')).timestamp() * 1000)
        end_time = int(datetime.fromisoformat(end_date.replace('Z', '')).timestamp() * 1000)
        funding_rates = self.info.funding_history(token, start_time, end_time)
        if not funding_rates:
            return pl.DataFrame()

        df = pl.DataFrame(funding_rates)
        df = df.with_columns([
            pl.from_epoch(pl.col('time'), time_unit='ms').alias('datetime'),
            pl.lit(token).alias('token')
        ])
        return df.select(['datetime', 'fundingRate', 'premium', 'token']).rename({'fundingRate': 'funding_rate'})

    def get_combined_data(self, token: str, start_date: str, end_date: str, time_interval: str = '1h') -> pl.DataFrame:
        """Returns a DataFrame with perpetual prices, spot prices, and funding rates."""
        perp_prices = self.get_perp_prices(token, start_date, end_date, time_interval)
        spot_prices = self.get_spot_prices(token, start_date, end_date, time_interval)
        funding_rates = self.get_funding_rates(token, start_date, end_date)

        # Rename columns to avoid conflicts
        perp_prices = perp_prices.rename({'open': 'perp_open', 'high': 'perp_high', 'low': 'perp_low', 'close': 'perp_close', 'volume': 'perp_volume', 'token': 'perp_token'})
        spot_prices = spot_prices.rename({'open': 'spot_open', 'high': 'spot_high', 'low': 'spot_low', 'close': 'spot_close', 'volume': 'spot_volume', 'token': 'spot_token'})
        funding_rates = funding_rates.rename({'token': 'funding_token'})

        # Join the dataframes
        df = perp_prices.join(spot_prices, on='datetime', how='outer', suffix='_spot')
        df = df.join(funding_rates, on='datetime', how='outer', suffix='_funding')

        return df
