# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_hyperliquid.ipynb.

# %% auto 0
__all__ = ['HyperliquidDataSource']

# %% ../nbs/02_hyperliquid.ipynb 3
from .datasource import DataSource
from pathlib import Path
from typing import List
import polars as pl
from hyperliquid.info import Info
from hyperliquid.utils import constants
import logging
from datetime import datetime, timedelta
import eth_account
import json

# %% ../nbs/02_hyperliquid.ipynb 4
class HyperliquidDataSource(DataSource):
    """A data source for Hyperliquid."""

    def __init__(self, data_folder: Path, config_path: str = '../config_hyperliquid.json'):
        super().__init__(data_folder)
        self.info = self._setup(config_path)

    def _setup(self, config_path: str):
        with open(config_path) as f:
            config = json.load(f)
        account = eth_account.Account.from_key(config["secret_key"])
        address = config.get("account_address") or account.address
        logging.info(f"Running with account address: {address}")
        return Info(constants.MAINNET_API_URL, skip_ws=True)

    def get_tokens(self) -> List[str]:
        """Returns a list of available tokens."""
        meta = self.info.meta()
        return [coin['name'] for coin in meta['universe']]

    def get_perp_prices(self, token: str, start_date: str, end_date: str, time_interval: str = '1h') -> pl.DataFrame:
        """Returns a DataFrame of perpetual prices for a given token."""
        start_time = int(datetime.fromisoformat(start_date.replace('Z', '')).timestamp() * 1000)
        end_time = int(datetime.fromisoformat(end_date.replace('Z', '')).timestamp() * 1000)
        candles = self.info.candles_snapshot(token, time_interval, start_time, end_time)
        if not candles:
            return pl.DataFrame()
        
        df = pl.DataFrame(candles)
        df = df.with_columns([
            pl.from_epoch(pl.col('t'), time_unit='ms').alias('datetime'),
            pl.lit(token).alias('token')
        ])
        return df.select(['datetime', 'o', 'h', 'l', 'c', 'v', 'token']).rename({'o': 'open', 'h': 'high', 'l': 'low', 'c': 'close', 'v': 'volume'})

    def get_spot_prices(self, token: str, start_date: str, end_date: str, time_interval: str = '1h') -> pl.DataFrame:
        """Returns a DataFrame of spot prices for a given token."""
        # The hyperliquid API uses the same candles_snapshot function for spot prices, but with a different token format.
        # We need to find the correct ticker for the spot market.
        meta = self.info.spot_meta()
        spot_token = next((t for t in meta['universe'] if t['name'] == token), None)
        if not spot_token:
            raise ValueError(f"Spot token {token} not found.")

        return self.get_perp_prices(spot_token['name'], start_date, end_date, time_interval)

    def get_funding_rates(self, token: str, start_date: str, end_date: str) -> pl.DataFrame:
        """Returns a DataFrame of funding rates for a given token."""
        start_time = int(datetime.fromisoformat(start_date.replace('Z', '')).timestamp() * 1000)
        end_time = int(datetime.fromisoformat(end_date.replace('Z', '')).timestamp() * 1000)
        funding_rates = self.info.funding_history(token, start_time, end_time)
        if not funding_rates:
            return pl.DataFrame()

        df = pl.DataFrame(funding_rates)
        df = df.with_columns([
            pl.from_epoch(pl.col('time'), time_unit='ms').alias('datetime'),
            pl.lit(token).alias('token')
        ])
        return df.select(['datetime', 'fundingRate', 'premium', 'token']).rename({'fundingRate': 'funding_rate'})

