# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/kraken.ipynb.

# %% auto #0
__all__ = ['retry_fetch_ohlcv', 'scrape_ohlcv', 'ohlcv_to_df', 'kraken_ohlcv', 'kraken_usd_tokens', 'save_file',
           'symbol_to_file_name', 'file_name_to_symbol', 'kraken_to_file']

# %% ../nbs/kraken.ipynb #2cbd5fbf
import os
import time
import datetime as dt
from datetime import datetime
import pandas as pd
import ccxt

# %% ../nbs/kraken.ipynb #4a92ef4d
def retry_fetch_ohlcv(exchange, max_retries, symbol, timeframe, since, limit, verbose=False):
    """
    Fetch a single page of OHLCV candles from an exchange, retrying on failure.

    Args:
        exchange (ccxt.Exchange): Instantiated ccxt exchange object
        max_retries (int): Maximum number of retries before raising the last error
        symbol (str): Trading pair symbol (e.g. "BTC/USD")
        timeframe (str): Candle timeframe (e.g. "1m", "1h", "1d")
        since (int): Start time in milliseconds since epoch (UTC)
        limit (int): Maximum number of candles to fetch
        verbose (bool, optional): If True, prints progress messages. Defaults to False

    Returns:
        list: List of OHLCV candles [timestamp_ms, open, high, low, close, volume]

    Raises:
        Exception: The last ccxt error if all retries fail
    """
    num_retries = 0
    while num_retries <= max_retries:
        try:
            ohlcv = exchange.fetch_ohlcv(symbol=symbol, timeframe=timeframe, since=since, limit=limit)
            if verbose and len(ohlcv):
                print(f"Fetched {len(ohlcv)} {symbol} candles from "
                      f"{exchange.iso8601(ohlcv[0][0])} to {exchange.iso8601(ohlcv[-1][0])}")
            time.sleep(exchange.rateLimit / 1000)
            return ohlcv
        except Exception as error:
            num_retries += 1
            if num_retries > max_retries:
                raise
            print(f"Error fetching {symbol}: {error}. Retry {num_retries}/{max_retries}")
            time.sleep(2)

# %% ../nbs/kraken.ipynb #4246bdd1
def scrape_ohlcv(exchange, symbol, timeframe, since, end=None, max_retries=3, limit=720, verbose=False):
    """
    Download OHLCV candles in pages of `limit` bars between `since` and `end`.

    Args:
        exchange (ccxt.Exchange): Instantiated ccxt exchange object (markets loaded)
        symbol (str): Trading pair symbol (e.g. "BTC/USD")
        timeframe (str): Candle timeframe (e.g. "1m", "1h", "1d")
        since (int or str): Start time in milliseconds since epoch or ISO 8601 string
        end (int or str, optional): End time in milliseconds or ISO 8601 string.
            Defaults to now.
        max_retries (int, optional): Retries per page. Defaults to 3
        limit (int, optional): Candles per request. Defaults to 720 (Kraken maximum)
        verbose (bool, optional): If True, prints progress messages. Defaults to False

    Returns:
        list: List of OHLCV candles [timestamp_ms, open, high, low, close, volume]
    """
    if isinstance(since, str):
        since = exchange.parse8601(since)
    now = exchange.milliseconds()
    if end is None:
        end = now
    elif isinstance(end, str):
        end = exchange.parse8601(end)
    tf_ms = exchange.parse_timeframe(timeframe) * 1000
    all_ohlcv = []
    fetch_since = since
    remain_bars = (end - fetch_since) / tf_ms + 1  # +1 to include the end candle
    while fetch_since < min(end, now) and remain_bars > 0:
        batch = int(min(limit, remain_bars))
        if batch < 1:
            break
        ohlcv = retry_fetch_ohlcv(exchange, max_retries, symbol, timeframe, fetch_since, batch, verbose=verbose)
        all_ohlcv = all_ohlcv + ohlcv
        fetch_since = fetch_since + batch * tf_ms
        remain_bars = remain_bars - batch
        if not ohlcv:
            break
    return exchange.filter_by_since_limit(all_ohlcv, since, None, key=0)

# %% ../nbs/kraken.ipynb #41eeaa12
def ohlcv_to_df(ohlcv, symbol):
    """
    Convert a raw ccxt OHLCV list into a tidy DataFrame.

    Args:
        ohlcv (list): List of candles [timestamp_ms, open, high, low, close, volume]
        symbol (str): Trading pair symbol added as the `pair` column

    Returns:
        pandas.DataFrame: DataFrame with columns:
            - datetime: Candle timestamp (UTC, timezone-aware)
            - open, high, low, close, volume: OHLCV values
            - pair: Trading pair symbol
        Sorted by datetime with duplicate timestamps removed.
    """
    df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    df['datetime'] = pd.to_datetime(df['timestamp'], unit='ms', utc=True)
    df['pair'] = symbol
    df = df.drop(columns=['timestamp'])
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'pair']]
    df = df.drop_duplicates(subset='datetime').sort_values('datetime').reset_index(drop=True)
    return df

# %% ../nbs/kraken.ipynb #06ad8ea9
def kraken_ohlcv(symbol='BTC/USD', timeframe='1h', since=None, end=None,
                 max_retries=3, limit=720, exchange=None, verbose=False):
    """
    Download OHLCV candles for a symbol from Kraken.

    Args:
        symbol (str, optional): Trading pair symbol. Defaults to "BTC/USD"
        timeframe (str, optional): Candle timeframe. Defaults to "1h"
        since (int or str, optional): Start time (ms since epoch or ISO 8601).
            If None, downloads the most recent ~`limit` candles (Kraken only
            serves about 720 recent candles per timeframe).
        end (int or str, optional): End time (ms or ISO 8601). Defaults to now
        max_retries (int, optional): Retries per page. Defaults to 3
        limit (int, optional): Candles per request. Defaults to 720
        exchange (ccxt.kraken, optional): Reusable exchange instance. If None, a new one is created
        verbose (bool, optional): If True, prints progress messages. Defaults to False

    Returns:
        pandas.DataFrame: Tidy OHLCV DataFrame (see `ohlcv_to_df`)
    """
    if exchange is None:
        exchange = ccxt.kraken({'enableRateLimit': True})
        exchange.load_markets()
    if since is None:
        tf_ms = exchange.parse_timeframe(timeframe) * 1000
        since = exchange.milliseconds() - (limit - 20) * tf_ms
    ohlcv = scrape_ohlcv(exchange, symbol, timeframe, since, end=end,
                         max_retries=max_retries, limit=limit, verbose=verbose)
    return ohlcv_to_df(ohlcv, symbol)

# %% ../nbs/kraken.ipynb #9dffaeb2
def kraken_usd_tokens(exchange=None):
    """
    Retrieves all active Kraken spot trading pairs quoted in USD.

    Args:
        exchange (ccxt.kraken, optional): Reusable exchange instance. If None, a new one is created

    Returns:
        pandas.DataFrame: DataFrame with columns:
            - id: Kraken market id (e.g. 'XBTUSD')
            - symbol: Unified ccxt symbol (e.g. 'BTC/USD')
            - base: Base currency (e.g. 'BTC')
            - quote: Always 'USD' for this filtered dataset
            - active: Whether the market is currently active
    """
    if exchange is None:
        exchange = ccxt.kraken({'enableRateLimit': True})
    markets = exchange.load_markets()
    rows = [{'id': m['id'], 'symbol': m['symbol'], 'base': m['base'],
             'quote': m['quote'], 'active': m.get('active', True)}
            for m in markets.values() if m.get('spot', False) and m['quote'] == 'USD']
    return pd.DataFrame(rows)

# %% ../nbs/kraken.ipynb #c5aa8f41
def save_file(df, folder_path, file_name, type="parquet"):
    """
    Save a pandas DataFrame to a file in either CSV or Parquet format.

    Args:
        df (pandas.DataFrame): The DataFrame to save
        folder_path (str): Directory path where the file will be saved
        file_name (str): Name of the file without extension
        type (str, optional): File format - either "csv" or "parquet". Defaults to "parquet"

    The function saves the DataFrame to the specified path, handling the file extension automatically.
    For CSV files, the index is not saved. Creates the folder if it doesn't exist.
    """
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
    if type == "csv":
        df.to_csv(f"{folder_path}/{file_name}.csv", index=False)
    elif type == "parquet":
        df.to_parquet(f"{folder_path}/{file_name}.parquet")
    else:
        raise ValueError(f"Type {type} not supported. Use 'csv' or 'parquet'")

# %% ../nbs/kraken.ipynb #143a3dfd
def symbol_to_file_name(symbol, timeframe='1h'):
    """
    Convert a ccxt symbol and timeframe into a file name (without extension).

    Example: ('BTC/USD', '1h') -> 'BTC-USD_1h'
    """
    return f"{symbol.replace('/', '-')}_{timeframe}"

def file_name_to_symbol(file_name):
    """
    Convert a file name back into a ccxt symbol.

    Example: 'BTC-USD_1h.parquet' -> 'BTC/USD'
    """
    base = os.path.splitext(file_name)[0]
    pair = base.rsplit('_', 1)[0]
    return pair.replace('-', '/')

# %% ../nbs/kraken.ipynb #47575568
def kraken_to_file(folder_path="../data/kraken", token_list=['BTC/USD', 'ETH/USD'], type="parquet",
                   timeframe='1h', refresh_hours=24, all_tokens=True, pause=1, verbose=False):
    """
    Downloads and maintains historical Kraken OHLCV data, saving one file per pair.

    Args:
        folder_path (str): Path where pair data files will be stored, named after the
            exchange. Defaults to "../data/kraken"
        token_list (list): List of ccxt symbols to process. Defaults to ['BTC/USD', 'ETH/USD']
        type (str): File format to save data - either "csv" or "parquet". Defaults to "parquet"
        timeframe (str): Candle timeframe (e.g. "1m", "1h", "1d"). Defaults to "1h"
        refresh_hours (int): Hours of the most recent data to re-download when updating.
            Defaults to 24
        all_tokens (bool): If True, includes any additional pairs found in the folder path.
            Defaults to True
        pause (int): Seconds to wait between pairs. Defaults to 1
        verbose (bool): If True, prints download progress. Defaults to False

    The function:
    - Creates the folder_path if it doesn't exist
    - Date/Time is UTC
    - For each pair, checks if a data file exists:
        - If exists: Loads the file and appends new data, refreshing the last `refresh_hours`
        - If not exists: Downloads the maximum available history (~720 candles on Kraken)
    - Saves data in the specified format, handling duplicates and sorting by datetime
    """
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
    elif all_tokens:
        file_names = [f for f in os.listdir(folder_path)
                      if f.endswith(type) and f"_{timeframe}." in f]
        tokens_in_folder = [file_name_to_symbol(f) for f in file_names]
        token_list = list(set(token_list + tokens_in_folder))
    exchange = ccxt.kraken({'enableRateLimit': True})
    exchange.load_markets()
    for token in token_list:
        print(f"Processing {token}")
        file_name = symbol_to_file_name(token, timeframe)
        file_path = f"{folder_path}/{file_name}.{type}"
        try:
            if os.path.exists(file_path):
                if type == "csv":
                    df = pd.read_csv(file_path)
                    df['datetime'] = pd.to_datetime(df['datetime'], utc=True)
                elif type == "parquet":
                    df = pd.read_parquet(file_path)
                else:
                    raise ValueError(f"Type {type} not supported")
                last_date = pd.to_datetime(df['datetime'].max(), utc=True)
                since = last_date - pd.Timedelta(hours=refresh_hours)
                df = df[pd.to_datetime(df['datetime'], utc=True) < since]
                df_new = kraken_ohlcv(symbol=token, timeframe=timeframe,
                                      since=since.strftime('%Y-%m-%dT%H:%M:%SZ'),
                                      exchange=exchange, verbose=verbose)
                df = pd.concat([df, df_new])
                df = df.drop_duplicates(subset='datetime').sort_values('datetime').reset_index(drop=True)
            else:
                df = kraken_ohlcv(symbol=token, timeframe=timeframe,
                                  exchange=exchange, verbose=verbose)
            if not df.empty:
                save_file(df, folder_path, file_name, type)
        except Exception as e:
            print(f"Error processing {token}: {e}")
        if pause > 0:
            time.sleep(pause)
