# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/lighter.ipynb.

# %% auto #0
__all__ = ['LIGHTER_BASE_URL', 'LIGHTER_EXPLORER_URL', 'TIMEFRAME_TO_RESOLUTION', 'TIMEFRAME_TO_SECONDS', 'lighter_spot_markets',
           'retry_fetch_candles', 'scrape_candles', 'candles_to_df', 'lighter_candles', 'save_file',
           'symbol_to_file_name', 'file_name_to_symbol', 'lighter_to_file']

# %% ../nbs/lighter.ipynb #a1b2c3d4
import os
import time
import requests
import pandas as pd

LIGHTER_BASE_URL = "https://mainnet.zklighter.elliot.ai"
LIGHTER_EXPLORER_URL = "https://explorer.elliot.ai"

# %% ../nbs/lighter.ipynb #a1b2c3d5
TIMEFRAME_TO_RESOLUTION = {
    '1m': '1m', '5m': '5m', '15m': '15m',
    '1h': '1h', '4h': '4h', '1d': '1d',
}

TIMEFRAME_TO_SECONDS = {
    '1m': 60, '5m': 300, '15m': 900,
    '1h': 3600, '4h': 14400, '1d': 86400,
}

def _resolution_from_timeframe(timeframe):
    """Map a timeframe string (e.g. '1h') to a Lighter resolution string."""
    if timeframe not in TIMEFRAME_TO_RESOLUTION:
        raise ValueError(f"Unsupported timeframe '{timeframe}'. Supported: {list(TIMEFRAME_TO_RESOLUTION)}")
    return TIMEFRAME_TO_RESOLUTION[timeframe]

def _tf_seconds(timeframe):
    """Return the number of seconds for a given timeframe."""
    if timeframe not in TIMEFRAME_TO_SECONDS:
        raise ValueError(f"Unsupported timeframe '{timeframe}'. Supported: {list(TIMEFRAME_TO_SECONDS)}")
    return TIMEFRAME_TO_SECONDS[timeframe]

# %% ../nbs/lighter.ipynb #a1b2c3d6
def lighter_spot_markets(explorer_url=LIGHTER_EXPLORER_URL):
    """
    Retrieve all spot markets from Lighter via the explorer API.

    Args:
        explorer_url (str): Lighter explorer API base URL. Defaults to mainnet explorer.

    Returns:
        pandas.DataFrame: DataFrame with columns:
            - symbol: Trading pair symbol (e.g. 'LIT/USDC')
            - market_id: Integer market ID used for candle requests
    """
    resp = requests.get(f"{explorer_url}/api/markets")
    resp.raise_for_status()
    data = resp.json()
    rows = [{'symbol': m['symbol'], 'market_id': m['market_index']}
            for m in data if '/USDC' in m.get('symbol', '')]
    return pd.DataFrame(rows)

# %% ../nbs/lighter.ipynb #a1b2c3d7
def _symbol_to_market_id(symbol, explorer_url=LIGHTER_EXPLORER_URL):
    """Resolve a trading pair symbol (e.g. 'LIT/USDC') to its Lighter market_id."""
    markets = lighter_spot_markets(explorer_url=explorer_url)
    match = markets[markets['symbol'] == symbol]
    if match.empty:
        raise ValueError(f"Symbol '{symbol}' not found in Lighter spot markets. "
                         f"Available: {markets['symbol'].tolist()}")
    return int(match.iloc[0]['market_id'])

# %% ../nbs/lighter.ipynb #a1b2c3d8
def retry_fetch_candles(market_id, resolution, start_ts, end_ts, count_back=500,
                        max_retries=3, base_url=LIGHTER_BASE_URL, verbose=False):
    """
    Fetch a single page of candles from Lighter, retrying on failure.

    Args:
        market_id (int): Lighter market ID
        resolution (str): Candle resolution (e.g. '1h', '1d')
        start_ts (int): Start timestamp in seconds since epoch
        end_ts (int): End timestamp in seconds since epoch
        count_back (int): Number of candles to fetch (max 500). Defaults to 500
        max_retries (int): Maximum retries before raising. Defaults to 3
        base_url (str): Lighter API base URL
        verbose (bool): If True, prints progress. Defaults to False

    Returns:
        list: List of candle dicts with keys t (ms), o, h, l, c, v, V, i
    """
    num_retries = 0
    while num_retries <= max_retries:
        try:
            resp = requests.get(f"{base_url}/api/v1/candles", params={
                'market_id': market_id,
                'resolution': resolution,
                'start_timestamp': start_ts,
                'end_timestamp': end_ts,
                'count_back': count_back,
            })
            resp.raise_for_status()
            data = resp.json()
            candles = data.get('c', [])
            if verbose and candles:
                print(f"Fetched {len(candles)} candles (market_id={market_id}) from "
                      f"{pd.Timestamp(candles[0]['t'], unit='ms', tz='UTC')} "
                      f"to {pd.Timestamp(candles[-1]['t'], unit='ms', tz='UTC')}")
            return candles
        except Exception as error:
            num_retries += 1
            if num_retries > max_retries:
                raise
            print(f"Error fetching candles (market_id={market_id}): {error}. "
                  f"Retry {num_retries}/{max_retries}")
            time.sleep(2)

# %% ../nbs/lighter.ipynb #a1b2c3d9
def scrape_candles(market_id, timeframe, since, end=None, max_retries=3, limit=500,
                   base_url=LIGHTER_BASE_URL, verbose=False):
    """
    Download candles in pages of `limit` bars between `since` and `end`.

    Lighter's `count_back` parameter returns the most recent N candles before
    `end_timestamp`, so we paginate **backwards**: after each fetch, we move
    `end_timestamp` to just before the oldest candle received and repeat until
    we reach `since` or the API returns no more data.

    Args:
        market_id (int): Lighter market ID
        timeframe (str): Candle timeframe (e.g. '1m', '1h', '1d')
        since (int or str): Start time in seconds since epoch or ISO 8601 string
        end (int or str, optional): End time in seconds or ISO 8601. Defaults to now
        max_retries (int): Retries per page. Defaults to 3
        limit (int): Candles per request (max 500). Defaults to 500
        base_url (str): Lighter API base URL
        verbose (bool): If True, prints progress. Defaults to False

    Returns:
        list: List of candle dicts with keys t (ms), o, h, l, c, v, V, i
    """
    resolution = _resolution_from_timeframe(timeframe)
    tf_sec = _tf_seconds(timeframe)
    if isinstance(since, str):
        since = int(pd.Timestamp(since, tz='UTC').timestamp())
    now_sec = int(pd.Timestamp.now(tz='UTC').timestamp())
    if end is None:
        end = now_sec
    elif isinstance(end, str):
        end = int(pd.Timestamp(end, tz='UTC').timestamp())
    end = min(end, now_sec)
    all_candles = []
    fetch_end = end
    while fetch_end > since:
        candles = retry_fetch_candles(market_id, resolution, since, fetch_end,
                                       count_back=limit, max_retries=max_retries,
                                       base_url=base_url, verbose=verbose)
        if not candles:
            break
        all_candles.extend(candles)
        oldest_t_sec = candles[0]['t'] // 1000
        if oldest_t_sec <= since:
            break
        fetch_end = oldest_t_sec - tf_sec
        if verbose:
            print(f"  Paginating: {len(all_candles)} candles so far, "
                  f"next end={pd.Timestamp(fetch_end, unit='s', tz='UTC')}")
        time.sleep(0.1)
    return all_candles

# %% ../nbs/lighter.ipynb #a1b2c3da
def candles_to_df(candles, symbol):
    """
    Convert a list of Lighter candle dicts into a tidy DataFrame.

    Args:
        candles (list): List of candle dicts with keys t (ms), o, h, l, c, v
        symbol (str): Trading pair symbol added as the `pair` column

    Returns:
        pandas.DataFrame: DataFrame with columns:
            - datetime: Candle timestamp (UTC, timezone-aware)
            - open, high, low, close, volume: OHLCV values
            - pair: Trading pair symbol
        Sorted by datetime with duplicate timestamps removed.
    """
    rows = []
    for c in candles:
        rows.append({
            'timestamp': c['t'],
            'open': c.get('o', 0),
            'high': c.get('h', 0),
            'low': c.get('l', 0),
            'close': c.get('c', 0),
            'volume': c.get('v', 0),
        })
    df = pd.DataFrame(rows)
    if df.empty:
        df = pd.DataFrame(columns=['datetime', 'open', 'high', 'low', 'close', 'volume', 'pair'])
        return df
    df['datetime'] = pd.to_datetime(df['timestamp'], unit='ms', utc=True)
    df['pair'] = symbol
    df = df.drop(columns=['timestamp'])
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'pair']]
    df = df.drop_duplicates(subset='datetime').sort_values('datetime').reset_index(drop=True)
    return df

# %% ../nbs/lighter.ipynb #a1b2c3db
def lighter_candles(symbol='LIT/USDC', timeframe='1h', since=None, end=None,
                    max_retries=3, limit=500, base_url=LIGHTER_BASE_URL,
                    explorer_url=LIGHTER_EXPLORER_URL, verbose=False):
    """
    Download candles for a symbol from Lighter.

    Args:
        symbol (str, optional): Trading pair symbol (e.g. 'LIT/USDC'). Defaults to 'LIT/USDC'
        timeframe (str, optional): Candle timeframe. Defaults to '1h'
        since (int or str, optional): Start time (seconds since epoch or ISO 8601).
            If None, downloads the most recent ~`limit` candles.
        end (int or str, optional): End time (seconds or ISO 8601). Defaults to now
        max_retries (int, optional): Retries per page. Defaults to 3
        limit (int, optional): Candles per request (max 500). Defaults to 500
        base_url (str): Lighter API base URL
        explorer_url (str): Lighter explorer API base URL for market lookup
        verbose (bool, optional): If True, prints progress. Defaults to False

    Returns:
        pandas.DataFrame: Tidy OHLCV DataFrame (see `candles_to_df`)
    """
    market_id = _symbol_to_market_id(symbol, explorer_url=explorer_url)
    if since is None:
        tf_sec = _tf_seconds(timeframe)
        now_sec = int(pd.Timestamp.now(tz='UTC').timestamp())
        since = now_sec - (limit - 20) * tf_sec
    candles = scrape_candles(market_id, timeframe, since, end=end,
                             max_retries=max_retries, limit=limit,
                             base_url=base_url, verbose=verbose)
    return candles_to_df(candles, symbol)

# %% ../nbs/lighter.ipynb #a1b2c3e0
def save_file(df, folder_path, file_name, type="parquet"):
    """
    Save a pandas DataFrame to a file in either CSV or Parquet format.

    Args:
        df (pandas.DataFrame): The DataFrame to save
        folder_path (str): Directory path where the file will be saved
        file_name (str): Name of the file without extension
        type (str, optional): File format - either "csv" or "parquet". Defaults to "parquet"
    """
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
    if type == "csv":
        df.to_csv(f"{folder_path}/{file_name}.csv", index=False)
    elif type == "parquet":
        df.to_parquet(f"{folder_path}/{file_name}.parquet")
    else:
        raise ValueError(f"Type {type} not supported. Use 'csv' or 'parquet'")

# %% ../nbs/lighter.ipynb #a1b2c3e1
def symbol_to_file_name(symbol, timeframe='1h'):
    """
    Convert a symbol and timeframe into a file name (without extension).

    Example: ('LIT/USDC', '1h') -> 'LIT-USDC_1h'
    """
    return f"{symbol.replace('/', '-')}_{timeframe}"

def file_name_to_symbol(file_name):
    """
    Convert a file name back into a symbol.

    Example: 'LIT-USDC_1h.parquet' -> 'LIT/USDC'
    """
    base = os.path.splitext(file_name)[0]
    pair = base.rsplit('_', 1)[0]
    return pair.replace('-', '/')

# %% ../nbs/lighter.ipynb #a1b2c3e3
def lighter_to_file(folder_path="../data/lighter", token_list=['LIT/USDC'], type="parquet",
                    timeframe='1h', refresh_hours=24, first_date='2024-01-01T00:00:00Z',
                    all_tokens=True, pause=1, base_url=LIGHTER_BASE_URL,
                    explorer_url=LIGHTER_EXPLORER_URL, verbose=False):
    """
    Downloads and maintains historical Lighter candle data, saving one file per pair.

    Args:
        folder_path (str): Path where pair data files will be stored.
            Defaults to "../data/lighter"
        token_list (list): List of symbols to process. Defaults to ['LIT/USDC']
        type (str): File format to save data - either "csv" or "parquet". Defaults to "parquet"
        timeframe (str): Candle timeframe (e.g. "1m", "1h", "1d"). Defaults to "1h"
        refresh_hours (int): Hours of the most recent data to re-download when updating.
            Defaults to 24
        first_date (str): ISO 8601 start date used for the initial full-history download.
            Defaults to '2024-01-01T00:00:00Z'
        all_tokens (bool): If True, includes any additional pairs found in the folder path.
            Defaults to True
        pause (int): Seconds to wait between pairs. Defaults to 1
        base_url (str): Lighter API base URL
        explorer_url (str): Lighter explorer API base URL for market lookup
        verbose (bool): If True, prints download progress. Defaults to False

    The function:
    - Creates the folder_path if it doesn't exist
    - Date/Time is UTC
    - For each pair, checks if a data file exists:
        - If exists: Loads the file and appends new data, refreshing the last `refresh_hours`
        - If not exists: Downloads full history starting from `first_date`
    - Saves data in the specified format, handling duplicates and sorting by datetime
    """
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
    elif all_tokens:
        file_names = [f for f in os.listdir(folder_path)
                      if f.endswith(type) and f"_{timeframe}." in f]
        tokens_in_folder = [file_name_to_symbol(f) for f in file_names]
        token_list = list(set(token_list + tokens_in_folder))
    for token in token_list:
        print(f"Processing {token}")
        file_name = symbol_to_file_name(token, timeframe)
        file_path = f"{folder_path}/{file_name}.{type}"
        try:
            if os.path.exists(file_path):
                if type == "csv":
                    df = pd.read_csv(file_path)
                    df['datetime'] = pd.to_datetime(df['datetime'], utc=True)
                elif type == "parquet":
                    df = pd.read_parquet(file_path)
                else:
                    raise ValueError(f"Type {type} not supported")
                last_date = pd.to_datetime(df['datetime'].max(), utc=True)
                since = last_date - pd.Timedelta(hours=refresh_hours)
                df = df[pd.to_datetime(df['datetime'], utc=True) < since]
                df_new = lighter_candles(symbol=token, timeframe=timeframe,
                                         since=since.strftime('%Y-%m-%dT%H:%M:%SZ'),
                                         base_url=base_url, explorer_url=explorer_url,
                                         verbose=verbose)
                df = pd.concat([df, df_new])
                df = df.drop_duplicates(subset='datetime').sort_values('datetime').reset_index(drop=True)
            else:
                df = lighter_candles(symbol=token, timeframe=timeframe, since=first_date,
                                     base_url=base_url, explorer_url=explorer_url,
                                     verbose=verbose)
            if not df.empty:
                save_file(df, folder_path, file_name, type)
        except Exception as e:
            print(f"Error processing {token}: {e}")
        if pause > 0:
            time.sleep(pause)
